name: Build dist files
on:
  push:
    branches:
      - master

jobs:
  run:
    name: Build files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run Build
        run: bun run build

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Ciaran Walsh
          author_email: ciaran@joomla51.com
          message: "Add dist files"
          add: "dist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
